name: Docker Image CI

on:
  push:
    branches: [ 'develop',  'brianackley001**', 'bug**', 'issue**', 'hotfix**', 'feature**', 'release**', 'support**', 'version**' ]
  pull_request:
    branches: [ 'develop',  'brianackley001**', 'bug**', 'issue**', 'hotfix**', 'feature**', 'release**', 'support**', 'version**'  ]

permissions:
  contents: 'read'
  packages: 'write'
  
jobs:
  test:
    name: Build/Test Node App
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js version ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: Archive npm failure logs
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: npm-logs
        path: ~/.npm/_logs
        

  build:
    needs: test
    name: Build Docker Container
    runs-on: ubuntu-latest

    steps:  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      
      
      - name: Build and push container image to registry
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile
