# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - budgeting-app-client

on:
  push:
    branches:
      - feature-bug/26
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_5e7e721df8f14716a82c2225b177c9fb }}
        password: ${{ secrets.AzureAppService_ContainerPassword_b9f24dc387cf41899b81eae611ddd1fd }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_5e7e721df8f14716a82c2225b177c9fb }}/ghcr.io/brianackley001/budgeting-app-client:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'budgeting-app-client'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f9069d93250e4e48ae7de7943791c91e }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_5e7e721df8f14716a82c2225b177c9fb }}/ghcr.io/brianackley001/budgeting-app-client:${{ github.sha }}'