name: Build, Test, Deploy Docker Image CI

env:
  NODE_VERSION: '20.x'  
  AZURE_WEBAPP_NAME: budgeting-app-client
  VITE_API_URL: ${{ secrets.VITE_API_URL }}
  VITE_MSAL_CLIENT_ID: ${{ secrets.VITE_MSAL_CLIENT_ID }}
  VITE_MSAL_AUTHORITY: ${{ secrets.VITE_MSAL_AUTHORITY }}
  VITE_MSFT_APP_INSIGHTS_KEY: ${{ secrets.VITE_MSFT_APP_INSIGHTS_KEY }}
  VITE_MSFT_APP_INSIGHTS_CONN_STRING: ${{ secrets.VITE_MSFT_APP_INSIGHTS_CONN_STRING  }}
  VITE_TRANSACTION_PAGINATION_SET_SIZE: 5
  
on:
  push:
    branches: [ "main","feature**" ]

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  test:
    name: Build/Test Node App
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 21.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js version ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: Archive npm failure logs
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: npm-logs
        path: ~/.npm/_logs
        
 
  build:
      needs: test
      name: Build Docker Container
      runs-on: ubuntu-latest

      steps:
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Debug to console
          run: echo "Docker build-args _ VITE_API_URL = ${{ env.VITE_API_URL }} | VITE_MSAL_CLIENT_ID = ${{ env.VITE_MSAL_CLIENT_ID }} | VITE_MSAL_AUTHORITY = ${{ env.VITE_MSAL_AUTHORITY }} | VITE_MSFT_APP_INSIGHTS_KEY = ${{ env.VITE_MSFT_APP_INSIGHTS_KEY }} | VITE_MSFT_APP_INSIGHTS_CONN_STRING = ${{ env.VITE_MSFT_APP_INSIGHTS_CONN_STRING }} | VITE_TRANSACTION_PAGINATION_SET_SIZE = ${{ env.VITE_TRANSACTION_PAGINATION_SET_SIZE }}"
          

        - name: Log in to GitHub container registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Lowercase the repo name
          run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
        
        - name: Build and push container image to registry
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
            file: ./Dockerfile
            build-args: |
              VITE_API_URL: ${{ env.VITE_API_URL }}
              VITE_MSAL_CLIENT_ID: ${{ env.VITE_MSAL_CLIENT_ID }}
              VITE_MSAL_AUTHORITY: ${{ env.VITE_MSAL_AUTHORITY }}
              VITE_MSFT_APP_INSIGHTS_KEY: ${{ env.VITE_MSFT_APP_INSIGHTS_KEY }}
              VITE_MSFT_APP_INSIGHTS_CONN_STRING: ${{ env.VITE_MSFT_APP_INSIGHTS_CONN_STRING }}
              VITE_TRANSACTION_PAGINATION_SET_SIZE: ${{ env.VITE_TRANSACTION_PAGINATION_SET_SIZE }}


  deploy:
      runs-on: ubuntu-latest

      needs: build

      name: Deploy to Azure Web App

      environment:
        name: 'production'
        url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

      steps:
        - name: Lowercase the repo name
          run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

        - name: Deploy to Azure Web App
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v3
          with:
            app-name: ${{ env.AZURE_WEBAPP_NAME }}
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
